#   _____ __  __ _____     _____                 _        _               __  __           _
#  / ____|  \/  |  __ \   / ____|               | |      | |             |  \/  |         | |
# | (___ | \  / | |__) | | (___  _ __   ___  ___| |_ __ _| |_ ___  _ __  | \  / | ___   __| | ___
#  \___ \| |\/| |  ___/   \___ \| '_ \ / _ \/ __| __/ _` | __/ _ \| '__| | |\/| |/ _ \ / _` |/ _ \
#  ____) | |  | | |       ____) | |_) |  __/ (__| || (_| | || (_) | |    | |  | | (_) | (_| |  __/
# |_____/|_|  |_|_|      |_____/| .__/ \___|\___|\__\__,_|\__\___/|_|    |_|  |_|\___/ \__,_|\___|
#                               | |
#                               |_|

#If the command /s is enabled (/s enable overrules this)
enabled: true

#if players can change their fly speed in spectator mode
speed: true

#If a player receives the night vision effect while in spectator mode
night-vision: true

#If a player receives the conduit effect while in spectator mode
conduit: true

#the max speed a player is allowed to go (Minimum 1)
max-speed: 5

#If when a player logs on in spectator mode they will be teleported back
teleport-back: false

#The ability to toggle the effects in spectator mode
seffect: true

#Whether to enforce the worlds
enforce-worlds: false
#The names of the worlds spectator mode is allowed in
worlds-allowed: [world, world_nether, world_the_end]

#If the y level is limited to the number in y-level in spectator mode
enforce-y: false

#see above (players can not go below this level)
y-level: 0

#If a player is not allowed to go through non-see-through able blocks in spectator mode
disallow-non-transparent-blocks: false

#If a player is not allowed to go through blocks in spectator mode
disallow-all-blocks: false

#Whether to make it so players can not go past a certain distance in spectator mode. The permission spectator-bypass bypasses this
enforce-distance: false

#See above (blocks)
distance: 64

#Prevents players from using the spectator teleport hot bar
prevent-teleport: false
#Prevents these commands from being executed unless you have the spectator-bypass permission. Example list: [back, return, home, homes, tpaccept, tpyes, warp, warps]
bad-commands: []



#Message when gamemode set to spectator mode
spectator-mode-message: '&9Setting gamemode to &b&lSPECTATOR MODE'

#Message when gamemode set to survival mode
survival-mode-message: '&9Setting gamemode to &b&lSURVIVAL MODE'

#Message when user preforms the command while falling (error message)
falling-message: '&cHey you &lcan not &r&cdo that while falling!'

#Message when user preforms command in world it is not allowed in
world-message: '&cHey you&l can not &r&cdo that in that world!'

#Message when user does not have permission to execute the command
permission-message: '&cYou do not have permission to do that!'

#Message when spectator mode is disabled and the user runs the command
disabled-message: '&cSpectator Mode is &lnot &r&cenabled by the server!'

#Message when a non-player runs the command with no arguments
console-message: '&cYou are &lnot &ca player!'

#Message when spectator mode has been disabled
disable-message: '&dSpectator mode has been &ldisabled'

#Message when spectator mode has been enabled
enable-message: '&dSpectator mode has been &lenabled'

#Message when the config.yml is reloaded
reload-message: '&bThe config file has been reloaded!'

#Message when the speed is set. Speed is added at the end
speed-message: '&bSpeed has been set to '

#Message sent when an invalid speed is said
invalid-speed-message: '&cThat is not a valid speed'

#Message sent when an invalid player is forced into spectator mode
invalid-player-message: '&cThat is not a valid player'

#Message when forcing a player was successful. /target/ is the player
force-success: '&bSuccessfully forced /target/ into /s'

#Message when forcing a player was not successful. /target/ is the player
force-fail: '&cFailed to force /target/ into /s'

#Message sent when a player tries to use the /seffect when not in spectator mode
no-spectator-message: '&cYou did not preform the /s command'

#Message sent when a player tries to execute a command not allowed in spectator mode
bad-command-message: '&cYou can not execute that command while in spectator mode'